POST http://127.0.0.1:57329/api/veiculos-estoque
Content-Type: application/json

{"anoFabricacao": 2023, "cor": "Prata", "kilometragem": 100, "preco": 120000, "status": "Disponivel", "modeloId": "ab2c4025-d6b2-4cdb-ae1a-43392d9b56a2", "chassis": "CP500000000000003"}

HTTP 201
Connection: close
Content-Type: application/json; charset=utf-8
Date: Mon, 05 Oct 2026 01:20:35 GMT
Server: Kestrel
Location: http://127.0.0.1:57329/api/veiculos-estoque/b6a0e253-4f84-4911-bcc8-839228adfbde
Transfer-Encoding: chunked
api-supported-versions: 2.0
api-deprecated-versions: 1.0

{"id":"b6a0e253-4f84-4911-bcc8-839228adfbde","anoFabricacao":2023,"cor":"Prata","kilometragem":100,"preco":120000,"status":"Disponivel","chassis":"CP500000000000003","modeloId":"ab2c4025-d6b2-4cdb-ae1a-43392d9b56a2"}
