DELETE http://127.0.0.1:57329/api/veiculos-estoque/fb96f655-2d7a-4858-832e-570c311ca955?api-version=2.0

HTTP 204
Connection: close
Date: Mon, 05 Oct 2026 01:20:35 GMT
Server: Kestrel
api-supported-versions: 2.0
api-deprecated-versions: 1.0


