DELETE http://127.0.0.1:57329/api/veiculos-estoque/262feece-c1a3-48e8-bf6a-158a57ce5add?api-version=1.0

HTTP 204
Connection: close
Date: Mon, 05 Oct 2026 01:20:35 GMT
Server: Kestrel
api-supported-versions: 2.0
api-deprecated-versions: 1.0


