PUT http://127.0.0.1:57329/api/veiculos-estoque/fb96f655-2d7a-4858-832e-570c311ca955?api-version=2.0
Content-Type: application/json

{"anoFabricacao": 2023, "cor": "Azul", "kilometragem": 100, "preco": 120000, "status": "Disponivel", "modeloId": "ab2c4025-d6b2-4cdb-ae1a-43392d9b56a2", "chassis": "CP500000000000012"}

HTTP 200
Connection: close
Content-Type: application/json; charset=utf-8
Date: Mon, 05 Oct 2026 01:20:35 GMT
Server: Kestrel
Transfer-Encoding: chunked
api-supported-versions: 2.0
api-deprecated-versions: 1.0

{"id":"fb96f655-2d7a-4858-832e-570c311ca955","anoFabricacao":2023,"cor":"Azul","kilometragem":100,"preco":120000,"status":"Disponivel","chassis":"CP500000000000012","modeloId":"ab2c4025-d6b2-4cdb-ae1a-43392d9b56a2"}
