GET http://127.0.0.1:57329/api/veiculos-estoque/fb96f655-2d7a-4858-832e-570c311ca955?api-version=2.0

HTTP 404
Connection: close
Content-Type: application/problem+json
Date: Mon, 05 Oct 2026 01:20:35 GMT
Server: Kestrel
Cache-Control: no-cache,no-store
Expires: -1
Pragma: no-cache
Transfer-Encoding: chunked
api-supported-versions: 2.0
api-deprecated-versions: 1.0

{"title":"Recurso não encontrado","status":404,"detail":"VeiculoEstoque com identificador 'fb96f655-2d7a-4858-832e-570c311ca955' não foi encontrado(a).","instance":"/api/veiculos-estoque/fb96f655-2d7a-4858-832e-570c311ca955","traceId":"0HNP2FRDU751P:00000001"}
