GET http://127.0.0.1:57329/health

HTTP 200
Connection: close
Content-Type: application/json; charset=utf-8
Date: Mon, 05 Oct 2026 01:20:36 GMT
Server: Kestrel
Cache-Control: no-store, no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Pragma: no-cache
Transfer-Encoding: chunked

{
  "status": "Healthy",
  "totalDuration": "00:00:00.0041580",
  "checks": [
    {
      "name": "self",
      "status": "Healthy",
      "duration": "00:00:00.0001088",
      "description": "A API est\u00E1 operando normalmente.",
      "tags": [
        "live"
      ]
    },
    {
      "name": "database",
      "status": "Healthy",
      "duration": "00:00:00.0036464",
      "tags": [
        "ready",
        "db"
      ]
    }
  ]
}
