GET http://127.0.0.1:57329/api/veiculos-estoque?pageSize=101

HTTP 400
Connection: close
Content-Type: application/problem+json
Date: Mon, 05 Oct 2026 01:20:35 GMT
Server: Kestrel
Cache-Control: no-cache,no-store
Expires: -1
Pragma: no-cache
Transfer-Encoding: chunked
api-supported-versions: 2.0
api-deprecated-versions: 1.0

{"title":"Parâmetro inválido","status":400,"detail":"O parâmetro 'pageSize' deve estar entre 1 e 100.","instance":"/api/veiculos-estoque","traceId":"0HNP2FRDU751D:00000001"}
