GET http://127.0.0.1:57329/api/veiculos-estoque?page=999&pageSize=100

HTTP 200
Connection: close
Content-Type: application/json; charset=utf-8
Date: Mon, 05 Oct 2026 01:20:35 GMT
Server: Kestrel
Transfer-Encoding: chunked
api-supported-versions: 2.0
api-deprecated-versions: 1.0

{"page":999,"pageSize":100,"totalItems":5,"totalPages":1,"hasPrevious":true,"hasNext":false,"items":[]}
