// <auto-generated />
using System;
using AutoHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AutoHub.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("VARCHAR(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Funcionarios", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarcaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelos", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR(300)");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("VeiculoClienteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("VeiculoClienteId");

                    b.ToTable("OrdensServico", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.OsPeca", b =>
                {
                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PecaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdemServicoId", "PecaId");

                    b.HasIndex("PecaId");

                    b.ToTable("OsPecas", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.OsServico", b =>
                {
                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoCobrado")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdemServicoId", "ServicoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("OsServicos", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoFabricante")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR(60)");

                    b.Property<int>("EstoqueQuantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Pecas", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicos", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.VeiculoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("VARCHAR(7)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("PlacaVeiculo")
                        .IsUnique();

                    b.ToTable("VeiculosCliente", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.VeiculoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("VARCHAR(17)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("Kilometragem")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(11,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.HasIndex("Chassis")
                        .IsUnique();

                    b.HasIndex("ModeloId");

                    b.ToTable("VeiculosEstoque", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoOriginal")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(9,2)");

                    b.Property<Guid>("VeiculoEstoqueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("VeiculoEstoqueId")
                        .IsUnique();

                    b.ToTable("Vendas", (string)null);
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Modelo", b =>
                {
                    b.HasOne("AutoHub.Domain.Entities.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.OrdemServico", b =>
                {
                    b.HasOne("AutoHub.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("OrdemServicos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoHub.Domain.Entities.VeiculoCliente", "VeiculoCliente")
                        .WithMany("OrdemServicos")
                        .HasForeignKey("VeiculoClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("VeiculoCliente");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.OsPeca", b =>
                {
                    b.HasOne("AutoHub.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("OsPecas")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoHub.Domain.Entities.Peca", "Peca")
                        .WithMany("OsPecas")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.OsServico", b =>
                {
                    b.HasOne("AutoHub.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("OsServicos")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoHub.Domain.Entities.Servico", "Servico")
                        .WithMany("OsServicos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.VeiculoCliente", b =>
                {
                    b.HasOne("AutoHub.Domain.Entities.Cliente", "Cliente")
                        .WithMany("VeiculosCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoHub.Domain.Entities.Modelo", "Modelo")
                        .WithMany("VeiculosCliente")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.VeiculoEstoque", b =>
                {
                    b.HasOne("AutoHub.Domain.Entities.Modelo", "Modelo")
                        .WithMany("VeiculosEstoque")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Venda", b =>
                {
                    b.HasOne("AutoHub.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoHub.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("Vendas")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoHub.Domain.Entities.VeiculoEstoque", "VeiculoEstoque")
                        .WithOne("Venda")
                        .HasForeignKey("AutoHub.Domain.Entities.Venda", "VeiculoEstoqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("VeiculoEstoque");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("VeiculosCliente");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("OrdemServicos");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Modelo", b =>
                {
                    b.Navigation("VeiculosCliente");

                    b.Navigation("VeiculosEstoque");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.OrdemServico", b =>
                {
                    b.Navigation("OsPecas");

                    b.Navigation("OsServicos");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Peca", b =>
                {
                    b.Navigation("OsPecas");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.Servico", b =>
                {
                    b.Navigation("OsServicos");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.VeiculoCliente", b =>
                {
                    b.Navigation("OrdemServicos");
                });

            modelBuilder.Entity("AutoHub.Domain.Entities.VeiculoEstoque", b =>
                {
                    b.Navigation("Venda");
                });
#pragma warning restore 612, 618
        }
    }
}
